### ISSUE TITLE
What now

### ISSUE THREAD

**Issue by Hayxu** [MayaChen350/LazniBludgeon#21]

**Comment by MayaChen350** [comment]
Ohh I was waiting for you to ask me or smth I'm still often thinking about it
Well the names and the abilities on the cards are missing (and I was unable to put them automatically or well not like I wanted, but I could try this again somehow though it was really really not working well for reasons that was beyond my understanding)

I thought about continuing the project using old versions of the cards with the text on but that would have be kinda not right

So I let that on hold until well...... for an undetermined amount of time
tho it's the thing I passed the most time on so I was sad that I couldn't continue it and mayhaps finish it one day

**Comment by Hayxu** [comment]
Well I'm currently switching between comic art and my new project, bludgeon being on halt/abandoned, due mainly to well, hardly any communication

**Comment by Hayxu** [comment]
I thought of inviting you into LuckyBois Studio, but didn't cuz I don't think it comes in your interests

**Comment by MayaChen350** [comment]
meh
I'm still in the middle of finals
I wanna work on embedded systems and web this summer mostly tho
(probably should find a job tho aaa)
I'll see after my session ends ig

**Comment by Hayxu** [comment]
Eh not really interested in getting you in anyway, which is also why I didn't asked
Bing's just there cuz "heck with it"
He's a director, as in, he owns some of the Laznis, so his point of view _does_ matter
The studio is as I said to Bing "Me, and half of your corpse laying on the floor"
You don't do music, neither art, and I don't think you do storytelling anymore.
The only thing that up your alley is _somewhat_ making video games, but I don't think that's the type of stuff you do?
Well you certainly could, and probably better than me, but like you said, not now anyway

**Comment by Hayxu** [comment]
closing this
